/* SPDX-License-Identifier: BSD-3-Clause */
/*
 * Minimal WASI wrapper for ELF objects generated by Wasker.
 */

#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

extern void wasker_main(void);

static uintptr_t linear_memory_base;
static int linear_memory_block_num;

#define LINEAR_MEMORY_BLOCK_SIZE (64 * 1024)
#define LINEAR_MEMORY_BLOCK_NUM_MAX 32

typedef struct {
	uint32_t iov_base;
	uint32_t iov_len;
} IoVec;

/* WASI errno 0 */
enum {
	WASI_ESUCCESS = 0,
};

int fd_write(int fd, int buf_iovec_addr, int vec_len, int size_addr)
{
	IoVec *iovec = (IoVec *)(linear_memory_base + (uintptr_t)buf_iovec_addr);
	uint32_t written = 0;
	int i;
	(void)fd;

	for (i = 0; i < vec_len; i++) {
		const char *buf =
			(const char *)(linear_memory_base + (uintptr_t)iovec[i].iov_base);
		size_t len = (size_t)iovec[i].iov_len;
		size_t j;

		for (j = 0; j < len; j++)
			printf("%c", buf[j]);

		written += (uint32_t)len;
	}

	*(uint32_t *)(linear_memory_base + (uintptr_t)size_addr) = written;
	return WASI_ESUCCESS;
}

int environ_sizes_get(int env_count_addr, int env_buf_size_addr)
{
	*(uint32_t *)(linear_memory_base + (uintptr_t)env_count_addr) = 0;
	*(uint32_t *)(linear_memory_base + (uintptr_t)env_buf_size_addr) = 0;
	return WASI_ESUCCESS;
}

int environ_get(int env_addrs, int env_buf_addr)
{
	(void)env_addrs;
	(void)env_buf_addr;

	return WASI_ESUCCESS;
}

void proc_exit(int code)
{
	exit(code);
}

long memory_base(void)
{
	void *memory;

	memory = calloc(LINEAR_MEMORY_BLOCK_NUM_MAX, LINEAR_MEMORY_BLOCK_SIZE);
	if (!memory)
		return 0;

	linear_memory_base = (uintptr_t)memory;
	linear_memory_block_num = 0;
	return (long)linear_memory_base;
}

long memory_grow(long num)
{
	int old = linear_memory_block_num;

	if (num < 0)
		return -1;

	if (LINEAR_MEMORY_BLOCK_NUM_MAX < linear_memory_block_num + num)
		return -1;

	linear_memory_block_num += (int)num;
	return old;
}

int main(int argc __attribute__((unused)),
	 char *argv[] __attribute__((unused)))
{
	wasker_main();
	return 0;
}
